version: '3'
services:
  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: stories-nginx
    ports:
      - 6080:80
    volumes:
      - .:/var/stories-server
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stories-server
    depends_on:
      - php

  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
      args: 
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    container_name: stories-php
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/stories-server/stories-upload.json
    volumes:
      - .:/var/stories-server
    networks:
      - stories-server
    depends_on:
      - db
    working_dir: /var/stories-server

  # DB
  db:
    image: mysql:5.7
    container_name: stories-db
    ports:
      - 6306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Lmx82yFCKrWFYUs'
    volumes:
      - ./db/volume:/var/lib/mysql
    networks:
      - stories-server

  # Adminer
  adminer:
    image: adminer
    container_name: stories-adminer
    restart: always
    ports:
      - 6001:8080
    networks:
      - stories-server
    depends_on:
      - db

networks:
  stories-server:
    driver: bridge